// All badge definitions — static, never written to Firestore
// stat: key on the stats object from travelStats.js (now includes booksLogged)
// custom: true — badge has special award logic, not a simple stat >= required check

export const BADGES = [
  // ── FOUNDER'S CIRCLE (first 100 accounts + 1 favorite book) ─────────────
  {
    id: 'founders-circle',
    category: 'founders',
    name: "Founder's Circle",
    description: 'One of the first 100 book lovers on The Literary Roads. Add a favorite book to your profile to claim this badge.',
    shareText: "I'm a Founding Member of The Literary Roads! Charter member from day one. 🏆",
    icon: '🏆',
    color: '#FFD700',
    stat: null,     // custom award logic — see badgeChecker.checkAndAwardFoundersBadge
    required: null,
    custom: true,
  },

  // ── TRAVEL (total check-ins) ─────────────────────────────────────────────
  {
    id: 'first-stop',
    category: 'travel',
    name: 'First Stop',
    description: 'Parked your literary car for the very first time.',
    shareText: 'Just earned the First Stop badge on The Literary Roads! 📍',
    icon: '📍',
    color: '#FF4E00',
    stat: 'totalCheckIns',
    required: 1,
  },
  {
    id: 'road-tripper',
    category: 'travel',
    name: 'Road Tripper',
    description: 'Five stops on the literary road.',
    shareText: 'Earned Road Tripper on The Literary Roads — 5 stops down! 🚗',
    icon: '🚗',
    color: '#FF4E00',
    stat: 'totalCheckIns',
    required: 5,
  },
  {
    id: 'road-warrior',
    category: 'travel',
    name: 'Road Warrior',
    description: 'Ten check-ins — the open road is calling your name.',
    shareText: 'I\'m a Road Warrior on The Literary Roads! 10 literary stops explored 🛣️',
    icon: '🛣️',
    color: '#FF4E00',
    stat: 'totalCheckIns',
    required: 10,
  },
  {
    id: 'literary-explorer',
    category: 'travel',
    name: 'Literary Explorer',
    description: '25 stops on your literary journey.',
    shareText: '25 literary stops explored — earned Literary Explorer on The Literary Roads! 🗺️',
    icon: '🗺️',
    color: '#FF4E00',
    stat: 'totalCheckIns',
    required: 25,
  },
  {
    id: 'vagabond',
    category: 'travel',
    name: 'Vagabond',
    description: '50 check-ins — a true literary nomad.',
    shareText: '50 check-ins! I\'m a Vagabond on The Literary Roads ✨',
    icon: '✈️',
    color: '#FF4E00',
    stat: 'totalCheckIns',
    required: 50,
  },

  // ── BOOKSTORES ────────────────────────────────────────────────────────────
  {
    id: 'first-shelf',
    category: 'bookstore',
    name: 'First Shelf',
    description: 'Visited your first independent bookstore.',
    shareText: 'Just checked in at my first independent bookstore on The Literary Roads! 📚',
    icon: '📚',
    color: '#40E0D0',
    stat: 'bookstoresVisited',
    required: 1,
  },
  {
    id: 'bibliophile',
    category: 'bookstore',
    name: 'Bibliophile',
    description: 'Five independent bookstores explored.',
    shareText: 'Earned Bibliophile on The Literary Roads — 5 indie bookstores explored! 🔖',
    icon: '🔖',
    color: '#40E0D0',
    stat: 'bookstoresVisited',
    required: 5,
  },
  {
    id: 'stack-master',
    category: 'bookstore',
    name: 'Stack Master',
    description: 'Ten independent bookstores visited.',
    shareText: '10 indie bookstores in — I\'m a Stack Master on The Literary Roads! 🏛️',
    icon: '🏛️',
    color: '#40E0D0',
    stat: 'bookstoresVisited',
    required: 10,
  },
  {
    id: 'book-pilgrim',
    category: 'bookstore',
    name: 'Book Pilgrim',
    description: '25 bookstores — you are the pilgrimage.',
    shareText: '25 bookstores visited! Earned Book Pilgrim on The Literary Roads 🌟',
    icon: '🌟',
    color: '#40E0D0',
    stat: 'bookstoresVisited',
    required: 25,
  },

  // ── CAFES ─────────────────────────────────────────────────────────────────
  {
    id: 'coffee-break',
    category: 'cafe',
    name: 'Coffee Break',
    description: 'Found your first literary cafe.',
    shareText: 'Found my first literary cafe on The Literary Roads! ☕',
    icon: '☕',
    color: '#C0C0C0',
    stat: 'cafesVisited',
    required: 1,
  },
  {
    id: 'caffeine-reader',
    category: 'cafe',
    name: 'Caffeine & Pages',
    description: 'Five literary cafes discovered.',
    shareText: 'Earned Caffeine & Pages on The Literary Roads — 5 literary cafes! ☕📖',
    icon: '🫖',
    color: '#C0C0C0',
    stat: 'cafesVisited',
    required: 5,
  },

  // ── FESTIVALS ─────────────────────────────────────────────────────────────
  {
    id: 'festival-bound',
    category: 'festival',
    name: 'Festival Bound',
    description: 'Checked in at your first book festival.',
    shareText: 'Just attended my first book festival via The Literary Roads! 🎪',
    icon: '🎪',
    color: '#FF69B4',
    stat: 'festivalsAttended',
    required: 1,
  },
  {
    id: 'festival-hopper',
    category: 'festival',
    name: 'Festival Hopper',
    description: 'Three book festivals attended.',
    shareText: '3 book festivals down! Earned Festival Hopper on The Literary Roads 🎭',
    icon: '🎭',
    color: '#FF69B4',
    stat: 'festivalsAttended',
    required: 3,
  },

  // ── STATES ────────────────────────────────────────────────────────────────
  {
    id: 'state-hopper',
    category: 'states',
    name: 'State Hopper',
    description: 'Explored literary spots in 3 different states.',
    shareText: 'Literary road-tripping across 3 states! Earned State Hopper 🗽',
    icon: '🗽',
    color: '#FFD700',
    stat: 'statesExplored',
    required: 3,
  },
  {
    id: 'multi-state',
    category: 'states',
    name: 'Multi-State Traveler',
    description: 'Literary spots in 5 different states.',
    shareText: '5 states explored on The Literary Roads! Earned Multi-State Traveler 🌟',
    icon: '🌟',
    color: '#FFD700',
    stat: 'statesExplored',
    required: 5,
  },
  {
    id: 'coast-to-coast',
    category: 'states',
    name: 'Coast to Coast',
    description: 'Explored 10 states — the whole country is your library.',
    shareText: '10 states explored! Coast to Coast on The Literary Roads 🌎',
    icon: '🌎',
    color: '#FFD700',
    stat: 'statesExplored',
    required: 10,
  },

  // ── SEASONAL READING QUEST (re-earnable each year) ───────────────────────
  // seasonal: true — earned via checkSeasonalBadges; year field tracked in badge doc
  {
    id: 'spring-reader',
    category: 'seasonal',
    name: 'Spring Reader',
    description: 'Hit 25% of your yearly reading goal by March 31.',
    shareText: 'I\'m a Spring Reader on The Literary Roads — 25% of my reading goal done! 🌸',
    icon: '🌸',
    color: '#FF69B4',
    stat: null, required: null, custom: true, seasonal: true,
    threshold: 0.25, endMonth: 2,
  },
  {
    id: 'summer-scholar',
    category: 'seasonal',
    name: 'Summer Scholar',
    description: 'Hit 50% of your yearly reading goal by June 30.',
    shareText: 'Halfway through my reading quest! Summer Scholar badge earned on The Literary Roads ☀️',
    icon: '☀️',
    color: '#FFD700',
    stat: null, required: null, custom: true, seasonal: true,
    threshold: 0.50, endMonth: 5,
  },
  {
    id: 'fall-bibliophile',
    category: 'seasonal',
    name: 'Fall Bibliophile',
    description: 'Hit 75% of your yearly reading goal by September 30.',
    shareText: '75% of my reading quest done! Fall Bibliophile on The Literary Roads 🍂',
    icon: '🍂',
    color: '#FF8C00',
    stat: null, required: null, custom: true, seasonal: true,
    threshold: 0.75, endMonth: 8,
  },
  {
    id: 'winter-wanderer',
    category: 'seasonal',
    name: 'Winter Wanderer',
    description: 'Complete your yearly reading goal by December 31.',
    shareText: 'Reading quest complete! Earned Winter Wanderer on The Literary Roads ❄️',
    icon: '❄️',
    color: '#87CEEB',
    stat: null, required: null, custom: true, seasonal: true,
    threshold: 1.00, endMonth: 11,
  },
  {
    id: 'year-round-reader',
    category: 'seasonal',
    name: 'Year-Round Reader',
    description: 'Earned all 4 seasonal reading badges in the same year.',
    shareText: 'Year-Round Reader! All 4 seasonal reading badges earned on The Literary Roads 🏆',
    icon: '🏆',
    color: '#FFD700',
    stat: null, required: null, custom: true, seasonal: true,
    threshold: null, endMonth: 11,
  },

  // ── READING (books logged) ────────────────────────────────────────────────
  {
    id: 'first-read',
    category: 'reading',
    name: 'First Read',
    description: 'Logged your first book in the Book Log.',
    shareText: 'Started my reading log on The Literary Roads! 📖',
    icon: '📖',
    color: '#9B59B6',
    stat: 'booksLogged',
    required: 1,
  },
  {
    id: 'bookworm',
    category: 'reading',
    name: 'Bookworm',
    description: 'Five books in the log.',
    shareText: '5 books logged — I\'m a Bookworm on The Literary Roads! 🐛',
    icon: '🐛',
    color: '#9B59B6',
    stat: 'booksLogged',
    required: 5,
  },
  {
    id: 'page-turner',
    category: 'reading',
    name: 'Page Turner',
    description: 'Ten books logged — you can\'t put it down.',
    shareText: '10 books logged! Earned Page Turner on The Literary Roads 📑',
    icon: '📑',
    color: '#9B59B6',
    stat: 'booksLogged',
    required: 10,
  },
  {
    id: 'literary-mind',
    category: 'reading',
    name: 'Literary Mind',
    description: '25 books logged — a true literary mind.',
    shareText: '25 books logged on The Literary Roads — earning my Literary Mind badge! 🧠',
    icon: '🧠',
    color: '#9B59B6',
    stat: 'booksLogged',
    required: 25,
  },
];

export const BADGE_COUNT = BADGES.length;

// Quick lookup by id
export const BADGE_MAP = Object.fromEntries(BADGES.map(b => [b.id, b]));
